version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Node
  node:
    image: node:12
    working_dir: /var/www
    volumes:
      - ./:/var/www

  composer:
    image: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: install
